/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sjdcxqbgtinsocyypeyk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZGN4cWJndGluc29jeXlwZXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDEwMTcsImV4cCI6MjA3NTQ3NzAxN30.k88EgQt2kxQ0AN44zCtC17VnB-irnFjac6DNIi_-b8E"